include(${CMAKE_CURRENT_SOURCE_DIR}/common/env.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/common/apps.cmake OPTIONAL RESULT_VARIABLE APPS_IS_FOUND)
if (APPS_IS_FOUND STREQUAL "NOTFOUND")
    message(FATAL_ERROR "APPS_IS_FOUND: ${APPS_IS_FOUND}")
endif()

include(${CMAKE_CURRENT_SOURCE_DIR}/common/utils.cmake OPTIONAL RESULT_VARIABLE UTILS_IS_FOUND)
if (UTILS_IS_FOUND STREQUAL "NOTFOUND")
    message(FATAL_ERROR "UTILS_IS_FOUND: ${${UTILS_IS_FOUND}}")
endif()


include(${CMAKE_CURRENT_SOURCE_DIR}/common/node.cmake OPTIONAL RESULT_VARIABLE NODE_IS_FOUND)
if (NODE_IS_FOUND STREQUAL "NOTFOUND")
	message(FATAL_ERROR "NODE_IS_FOUND:{${NODE_IS_FOUND}")
endif()

setup_node("18.18.0")

execute_process(
	COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/common/exec-detached.bat 
	${VSCODE}
	"."
	WORKING_DIRECTORY "$ENV{USERPROFILE}\\Downloads")