include(${CMAKE_CURRENT_SOURCE_DIR}/common/utils.cmake OPTIONAL RESULT_VARIABLE UTILS_IS_FOUND)
if (UTILS_IS_FOUND STREQUAL "NOTFOUND")
    message(FATAL_ERROR "UTILS_IS_FOUND: ${UTILS_IS_FOUND}")
endif()

execute_process(
	COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/common/get-vscode-latest-version.bat
	OUTPUT_VARIABLE TEMP
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_STRIP_TRAILING_WHITESPACE)
# string(STRIP ${TEMP} TEMP)

get_filename_component(FILE_NAME_WITHOUT_EXTENSION
	${TEMP}
	NAME_WLE)
	
if(NOT EXISTS "$ENV{USERPROFILE}/Downloads/${FILE_NAME_WITHOUT_EXTENSION}")
	execute_process(
		COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/common/download-vscode-latest-version.bat
		OUTPUT_VARIABLE TEMP
		WORKING_DIRECTORY "$ENV{USERPROFILE}\\Downloads"
		OUTPUT_STRIP_TRAILING_WHITESPACE)
else()
	message("found vscode")
endif()


set(VSCODE "$ENV{USERPROFILE}\\Downloads\\${FILE_NAME_WITHOUT_EXTENSION}\\Code.exe")